// CATÁLOGO EDITÁVEL DO POLO UNIFIL IGUARAÇU
// Para acrescentar ou alterar cursos, edite somente os objetos abaixo.
const CURSOS = [
 {nome:'Administração',categoria:'Graduação',modalidade:'Online',duracao:'4 anos',descricao:'Formação para compreender e aplicar conhecimentos de gestão, planejamento, pessoas, processos e negócios.',detalhes:'O curso desenvolve visão administrativa e capacidade para analisar situações, planejar ações, organizar recursos e apoiar decisões nas organizações.',conteudos:['Gestão de pessoas','Administração financeira','Marketing','Planejamento','Processos organizacionais'],atuacao:'Empresas, comércio, serviços, instituições públicas e privadas e empreendedorismo.'},
 {nome:'Análise e Desenvolvimento de Sistemas',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos e meio',descricao:'Formação voltada ao desenvolvimento de sistemas, programação, bancos de dados e soluções tecnológicas.',detalhes:'O estudante aprende fundamentos de desenvolvimento de software e participa da construção, análise e manutenção de soluções digitais.',conteudos:['Programação','Banco de dados','Engenharia de software','Desenvolvimento web','Análise de sistemas'],atuacao:'Desenvolvimento de software, análise de sistemas, tecnologia e suporte a soluções digitais.'},
 {nome:'Ciências Contábeis',categoria:'Graduação',modalidade:'Online',duracao:'4 anos',descricao:'Formação para compreender contabilidade, patrimônio, demonstrações, custos e informações para tomada de decisão.',detalhes:'O curso prepara o estudante para interpretar informações contábeis e compreender os processos relacionados à gestão patrimonial e financeira.',conteudos:['Contabilidade','Custos','Auditoria','Finanças','Legislação'],atuacao:'Escritórios contábeis, empresas, áreas financeiras, controladoria e serviços contábeis.'},
 {nome:'Pedagogia',categoria:'Licenciatura',modalidade:'Online',duracao:'4 anos',descricao:'Formação para atuação na educação, processos de ensino e aprendizagem e gestão dos espaços educativos.',detalhes:'O estudante conhece fundamentos da educação, metodologias, planejamento, avaliação e diferentes dimensões do trabalho pedagógico.',conteudos:['Didática','Alfabetização','Psicologia da educação','Currículo','Gestão escolar'],atuacao:'Educação infantil, anos iniciais, espaços educativos e diferentes áreas de atuação pedagógica.'},
 {nome:'Gestão Financeira',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação voltada à análise financeira, planejamento, controle e apoio às decisões econômicas das organizações.',detalhes:'O curso aborda ferramentas e conceitos para acompanhar recursos, custos, orçamento, investimentos e indicadores financeiros.',conteudos:['Finanças','Orçamento','Custos','Investimentos','Análise financeira'],atuacao:'Setor financeiro, empresas, bancos, consultoria e áreas administrativas.'},
 {nome:'Gestão de Recursos Humanos',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender pessoas, relações de trabalho, desenvolvimento profissional e processos de RH.',detalhes:'O estudante aprende a organizar processos relacionados às pessoas nas organizações e a compreender estratégias de desenvolvimento humano.',conteudos:['Recrutamento','Treinamento','Gestão de pessoas','Clima organizacional','Legislação trabalhista'],atuacao:'Recursos humanos, departamento pessoal, treinamento e desenvolvimento e gestão de pessoas.'},
 {nome:'Gestão Pública',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender administração pública, políticas, planejamento e gestão de recursos públicos.',detalhes:'O curso apresenta fundamentos de gestão e organização do setor público, com foco em planejamento e atuação responsável.',conteudos:['Administração pública','Políticas públicas','Planejamento','Orçamento público','Gestão'],atuacao:'Órgãos públicos, organizações sociais e áreas administrativas ligadas à gestão pública.'},
 {nome:'Logística',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para planejar e acompanhar fluxos de materiais, estoque, transporte, distribuição e operações.',detalhes:'O estudante aprende a analisar processos logísticos e buscar eficiência no fluxo de produtos e informações.',conteudos:['Estoque','Transportes','Compras','Distribuição','Cadeia de suprimentos'],atuacao:'Logística, transportadoras, indústria, comércio, centros de distribuição e operações.'},
 {nome:'Gestão Comercial',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação voltada a vendas, negociação, relacionamento com clientes e gestão de operações comerciais.',detalhes:'O curso desenvolve conhecimentos para planejar ações comerciais, compreender mercados e melhorar resultados de vendas.',conteudos:['Vendas','Negociação','Marketing','Comportamento do consumidor','Estratégias comerciais'],atuacao:'Vendas, comércio, atendimento, supervisão comercial e gestão de negócios.'},
 {nome:'Gestão da Qualidade',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender processos, melhoria contínua, indicadores e gestão da qualidade.',detalhes:'O estudante conhece ferramentas para acompanhar processos, identificar problemas e apoiar melhorias organizacionais.',conteudos:['Qualidade','Processos','Indicadores','Melhoria contínua','Gestão'],atuacao:'Indústria, serviços, empresas, processos, auditoria e áreas de qualidade.'},
 {nome:'Marketing',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender mercados, marcas, consumidores, comunicação e estratégias de marketing.',detalhes:'O curso aborda fundamentos para planejar ações de comunicação e relacionamento com diferentes públicos.',conteudos:['Marketing digital','Marca','Pesquisa de mercado','Comunicação','Comportamento do consumidor'],atuacao:'Marketing, comunicação, mídias, atendimento, vendas e gestão de marcas.'},
 {nome:'Inteligência Artificial',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação relacionada a conceitos, aplicações e soluções baseadas em inteligência artificial e dados.',detalhes:'O estudante entra em contato com fundamentos e aplicações tecnológicas ligadas à inteligência artificial.',conteudos:['IA','Dados','Algoritmos','Automação','Tecnologia'],atuacao:'Tecnologia, dados, automação, desenvolvimento de soluções e áreas digitais.'},
 {nome:'Segurança Cibernética',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação voltada à proteção de sistemas, informações, redes e ambientes digitais.',detalhes:'O curso apresenta conceitos de segurança da informação, redes e práticas de proteção de ambientes tecnológicos.',conteudos:['Segurança da informação','Redes','Proteção de dados','Sistemas','Gestão de riscos'],atuacao:'Segurança da informação, suporte, redes, tecnologia e gestão de riscos digitais.'},
 {nome:'História',categoria:'Licenciatura',modalidade:'Online',duracao:'4 anos',descricao:'Formação para estudar processos históricos, sociedades, culturas e diferentes interpretações do passado.',detalhes:'O estudante desenvolve leitura crítica de acontecimentos e processos históricos, relacionando passado e sociedade.',conteudos:['História do Brasil','História geral','Historiografia','Cultura','Pesquisa histórica'],atuacao:'Docência, educação, pesquisa, cultura e instituições relacionadas ao patrimônio histórico.'},
 {nome:'Letras Português-Inglês',categoria:'Licenciatura',modalidade:'Online',duracao:'4 anos',descricao:'Formação para estudo das línguas portuguesa e inglesa, literatura, linguagem e ensino.',detalhes:'O curso desenvolve conhecimentos linguísticos e literários e fundamentos para o ensino das línguas.',conteudos:['Língua portuguesa','Língua inglesa','Literaturas','Linguística','Didática'],atuacao:'Docência, educação, produção textual, revisão e áreas relacionadas à linguagem.'}
];

// Carrega módulos de cursos detalhados sem alterar o catálogo existente.
(function(){
  function load(){
    if(document.getElementById('logisticaLoader')) return;
    const s=document.createElement('script');
    s.id='logisticaLoader';
    s.src='logistica.js';
    s.async=true;
    document.body.appendChild(s);
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',load,{once:true});
  else load();
})();
