// CATÁLOGO EDITÁVEL DO POLO UNIFIL IGUARAÇU
const CURSOS = [
 {nome:'Administração',categoria:'Graduação',modalidade:'Online',duracao:'4 anos',descricao:'Formação para compreender e aplicar conhecimentos de gestão, planejamento, pessoas, processos e negócios.',detalhes:'O curso desenvolve visão administrativa e capacidade para analisar situações, planejar ações, organizar recursos e apoiar decisões nas organizações.',conteudos:['Gestão de pessoas','Administração financeira','Marketing','Planejamento','Processos organizacionais'],atuacao:'Empresas, comércio, serviços, instituições públicas e privadas e empreendedorismo.'},
 {nome:'Análise e Desenvolvimento de Sistemas',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos e meio',descricao:'Formação voltada ao desenvolvimento de sistemas, programação, bancos de dados e soluções tecnológicas.',detalhes:'O estudante aprende fundamentos de desenvolvimento de software e participa da construção, análise e manutenção de soluções digitais.',conteudos:['Programação','Banco de dados','Engenharia de software','Desenvolvimento web','Análise de sistemas'],atuacao:'Desenvolvimento de software, análise de sistemas, tecnologia e suporte a soluções digitais.'},
 {nome:'Ciências Contábeis',categoria:'Graduação',modalidade:'Online',duracao:'4 anos',descricao:'Formação para compreender contabilidade, patrimônio, demonstrações, custos e informações para tomada de decisão.',detalhes:'O curso prepara o estudante para interpretar informações contábeis e compreender os processos relacionados à gestão patrimonial e financeira.',conteudos:['Contabilidade','Custos','Auditoria','Finanças','Legislação'],atuacao:'Escritórios contábeis, empresas, áreas financeiras, controladoria e serviços contábeis.'},
 {nome:'Pedagogia',categoria:'Licenciatura',modalidade:'EAD',duracao:'4 anos',descricao:'Formação para atuação na educação, preparando futuros pedagogos para o ensino, planejamento e gestão dos sistemas educacionais.',detalhes:'O curso considera a relação entre escola, estudante, família e comunidade e prepara para diferentes dimensões do trabalho pedagógico.',conteudos:['Ensino','Planejamento educacional','Gestão educacional','Orientação','Supervisão'],atuacao:'Educação infantil, anos iniciais, gestão, orientação, supervisão, psicopedagogia, empresas, hospitais, editoras, brinquedotecas e ONGs.'},
 {nome:'Gestão Financeira',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação voltada à análise financeira, planejamento, controle e apoio às decisões econômicas das organizações.',detalhes:'O curso aborda ferramentas e conceitos para acompanhar recursos, custos, orçamento, investimentos e indicadores financeiros.',conteudos:['Finanças','Orçamento','Custos','Investimentos','Análise financeira'],atuacao:'Setor financeiro, empresas, bancos, consultoria e áreas administrativas.'},
 {nome:'Gestão de Recursos Humanos',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender pessoas, relações de trabalho, desenvolvimento profissional e processos de RH.',detalhes:'O estudante aprende a organizar processos relacionados às pessoas nas organizações e a compreender estratégias de desenvolvimento humano.',conteudos:['Recrutamento','Treinamento','Gestão de pessoas','Clima organizacional','Legislação trabalhista'],atuacao:'Recursos humanos, departamento pessoal, treinamento e desenvolvimento e gestão de pessoas.'},
 {nome:'Gestão Pública',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender administração pública, políticas, planejamento e gestão de recursos públicos.',detalhes:'O curso apresenta fundamentos de gestão e organização do setor público, com foco em planejamento e atuação responsável.',conteudos:['Administração pública','Políticas públicas','Planejamento','Orçamento público','Gestão'],atuacao:'Órgãos públicos, organizações sociais e áreas administrativas ligadas à gestão pública.'},
 {nome:'Logística',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para planejar e acompanhar fluxos de materiais, estoque, transporte, distribuição e operações.',detalhes:'O estudante aprende a analisar processos logísticos e buscar eficiência no fluxo de produtos e informações.',conteudos:['Estoque','Transportes','Compras','Distribuição','Cadeia de suprimentos'],atuacao:'Logística, transportadoras, indústria, comércio, centros de distribuição e operações.'},
 {nome:'Gestão Comercial',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação voltada a vendas, negociação, relacionamento com clientes e gestão de operações comerciais.',detalhes:'O curso desenvolve conhecimentos para planejar ações comerciais, compreender mercados e melhorar resultados de vendas.',conteudos:['Vendas','Negociação','Marketing','Comportamento do consumidor','Estratégias comerciais'],atuacao:'Vendas, comércio, atendimento, supervisão comercial e gestão de negócios.'},
 {nome:'Gestão da Qualidade',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para compreender processos, melhoria contínua, indicadores e gestão da qualidade.',detalhes:'O estudante conhece ferramentas para acompanhar processos, identificar problemas e apoiar melhorias organizacionais.',conteudos:['Qualidade','Processos','Indicadores','Melhoria contínua','Gestão'],atuacao:'Indústria, serviços, empresas, processos, auditoria e áreas de qualidade.'},
 {nome:'Marketing',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação para gerir atividades de marketing, comunicação, estratégias, pesquisas e relacionamento com públicos.',detalhes:'O profissional formado pela UniFil desenvolve capacidade para diagnosticar problemas de gestão da comunicação, traçar estratégias de marketing e convertê-las em vendas, adesão à marca e alcance do público-alvo.',conteudos:['Marketing estratégico','Pesquisa de mercado','Comunicação integrada de marketing','Gestão da comunicação','Estratégias de marketing'],atuacao:'Empresas públicas e privadas, marketing estratégico, pesquisa de mercado, gerenciamento de ações decisórias e comunicação integrada de marketing.'},
 {nome:'Inteligência Artificial',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'Formação relacionada a conceitos, aplicações e soluções baseadas em inteligência artificial e dados.',detalhes:'O estudante entra em contato com fundamentos e aplicações tecnológicas ligadas à inteligência artificial.',conteudos:['IA','Dados','Algoritmos','Automação','Tecnologia'],atuacao:'Tecnologia, dados, automação, desenvolvimento de soluções e áreas digitais.'},
 {nome:'Segurança Cibernética',categoria:'Graduação',modalidade:'Tecnólogo',duracao:'2 anos',descricao:'O curso de Segurança Cibernética da UniFil EAD forma profissionais capazes de identificar, analisar e mitigar ameaças digitais em diferentes ambientes tecnológicos.',detalhes:'Com uma base sólida em redes, criptografia, monitoramento, governança e políticas de segurança, o estudante desenvolve competências para proteger sistemas, dados e infraestruturas críticas contra ataques e vulnerabilidades.',conteudos:['Redes','Criptografia','Monitoramento','Governança','Políticas de segurança','Análise de vulnerabilidades','Gestão de incidentes','Pentest','Auditorias','Proteção de dados','Conformidade'],atuacao:'Empresas de tecnologia, instituições financeiras, prestadoras de serviços de TI, órgãos governamentais, consultorias e setores de segurança corporativa.'},
 {nome:'História',categoria:'Licenciatura',modalidade:'Online',duracao:'4 anos',descricao:'Formação para estudar processos históricos, sociedades, culturas e diferentes interpretações do passado.',detalhes:'O estudante desenvolve leitura crítica de acontecimentos e processos históricos, relacionando passado e sociedade.',conteudos:['História do Brasil','História geral','Historiografia','Cultura','Pesquisa histórica'],atuacao:'Docência, educação, pesquisa, cultura e instituições relacionadas ao patrimônio histórico.'},
 {nome:'Letras Português-Inglês',categoria:'Licenciatura',modalidade:'Online',duracao:'4 anos',descricao:'Formação para estudo das línguas portuguesa e inglesa, literatura, linguagem e ensino.',detalhes:'O curso desenvolve conhecimentos linguísticos e literários e fundamentos para o ensino das línguas.',conteudos:['Língua portuguesa','Língua inglesa','Literaturas','Linguística','Didática'],atuacao:'Docência, educação, produção textual, revisão e áreas relacionadas à linguagem.'},
 {nome:'Matemática',categoria:'Licenciatura',modalidade:'Semipresencial',duracao:'4 anos',descricao:'Formação sólida em lógica, álgebra, cálculo, estatística e geometria, com desenvolvimento do raciocínio crítico e analítico.',detalhes:'O curso busca formar profissionais capazes de aplicar a matemática em contextos acadêmicos, científicos e tecnológicos.',conteudos:['Lógica','Álgebra','Cálculo','Estatística','Geometria'],atuacao:'Escolas, centros de pesquisa, empresas de tecnologia, setor financeiro, análise de dados e consultorias.'},
 {nome:'Mídias Sociais Digitais',categoria:'Graduação',modalidade:'EAD',duracao:'2 anos',descricao:'Formação para planejar, produzir e gerenciar conteúdos e estratégias nos ambientes digitais.',detalhes:'O estudante desenvolve competências em comunicação, marketing digital, análise de métricas, comportamento do usuário e gestão de comunidades online.',conteudos:['Comunicação digital','Marketing digital','Análise de métricas','Comportamento do usuário','Gestão de comunidades online'],atuacao:'Agências de comunicação, departamentos de marketing, empresas privadas, órgãos públicos, startups, ONGs, consultoria e atuação como social media independente.'},
 {nome:'Ministério Pastoral',categoria:'Graduação',modalidade:'EAD',duracao:'2 anos',descricao:'Formação tecnológica com estudo de temas práticos para a capacitação do Ministério Pastoral.',detalhes:'O curso oferece capacitação do Ministério Pastoral para pessoas relacionadas a igrejas e comunidades religiosas.',conteudos:['Capacitação pastoral','Pastoral','Aconselhamento','Discipulado','Formação religiosa'],atuacao:'Igrejas, instituições religiosas e eclesiásticas, pastoral, aconselhamento, discipulado e formação religiosa.'},
 {nome:'Processos Gerenciais',categoria:'Graduação',modalidade:'EAD',duracao:'2 anos',descricao:'Formação para o gerenciamento de organizações, elaboração de planos de negócios e relatórios gerenciais e tomada de decisões.',detalhes:'O curso desenvolve capacidade para planejar ações, controlar e avaliar resultados e atuar em áreas fundamentais como Gestão de Pessoas, Logística, Finanças e Marketing.',conteudos:['Planos de negócios','Relatórios gerenciais','Tomada de decisões','Gestão de Pessoas','Logística','Finanças','Marketing'],atuacao:'Negócio próprio, áreas administrativa, contábil, financeira, recursos humanos, marketing e vendas, consultorias e assessorias, órgãos públicos e organizações do terceiro setor.'},
 {nome:'Relações Internacionais',categoria:'Graduação',modalidade:'EAD',duracao:'4 anos',descricao:'Formação para compreender as dinâmicas políticas, econômicas e culturais do sistema internacional.',detalhes:'O estudante desenvolve habilidades analíticas e estratégicas para atuar em ambientes globais e multiculturais.',conteudos:['Dinâmicas políticas internacionais','Dinâmicas econômicas internacionais','Dinâmicas culturais internacionais','Análise estratégica','Ambientes globais e multiculturais'],atuacao:'Órgãos governamentais, embaixadas, empresas multinacionais, ONGs, instituições financeiras, organismos internacionais e consultorias, nas áreas de comércio exterior, diplomacia, cooperação e políticas públicas.'}
];

(function(){
 function loadScript(id,src){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=true;document.body.appendChild(s)}
 function load(){loadScript('logisticaLoader','logistica.js');setTimeout(()=>loadScript('matematicaLoader','matematica.js'),900);setTimeout(()=>loadScript('marketingLoader','marketing.js'),1200);setTimeout(()=>loadScript('midiasSociaisLoader','midias-sociais-digitais.js'),1500);setTimeout(()=>loadScript('ministerioPastoralLoader','ministerio-pastoral.js'),1800);setTimeout(()=>loadScript('pedagogiaLoader','pedagogia.js'),2100);setTimeout(()=>loadScript('processosGerenciaisLoader','processos-gerenciais.js'),2400);setTimeout(()=>loadScript('relacoesInternacionaisLoader','relacoes-internacionais.js'),2700);setTimeout(()=>loadScript('segurancaCiberneticaLoader','seguranca-cibernetica.js'),3000)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();
