/* UniFil Polo Iguaraçu — Matemática Licenciatura */
(function(){
  function render(){
    const root=document.getElementById('cursoModulos') || document.querySelector('.courseSection .wrap');
    if(!root || document.getElementById('matematicaBlock')) return;
    const WA='https://wa.me/5544997239673';
    root.insertAdjacentHTML('beforeend',`<article class="unifilCourse" id="matematicaBlock"><div class="ucBadge">LICENCIATURA • SEMIPRESENCIAL</div><h3>Matemática</h3><p class="ucIntro">O curso de Matemática da UniFil oferece formação sólida em lógica, álgebra, cálculo, estatística e geometria, aliada ao desenvolvimento do raciocínio crítico e analítico. A formação busca preparar profissionais capazes de aplicar a matemática em contextos acadêmicos, científicos e tecnológicos.</p><div class="ucMeta"><span>Licenciatura</span><span>Semipresencial</span><span>4 anos</span></div><button class="ucBtn" type="button" data-mat-open>Ver informações do curso →</button><div class="ucPanel" data-mat-panel hidden><button class="ucClose" type="button" data-mat-close>← Fechar informações</button><h4>Matemática — informações do curso</h4><section><h5>Sobre o curso</h5><p>O curso de Matemática da UniFil oferece formação sólida em lógica, álgebra, cálculo, estatística e geometria, aliada ao desenvolvimento do raciocínio crítico e analítico.</p><p>O curso busca formar profissionais capazes de aplicar a matemática em contextos acadêmicos, científicos e tecnológicos.</p></section><section><h5>Quais áreas poderei atuar como profissional em Matemática?</h5><p>O egresso poderá atuar em escolas, centros de pesquisa, empresas de tecnologia, setor financeiro, análise de dados e consultorias.</p><p>Está apto a desenvolver soluções matemáticas para problemas práticos e teóricos. Assim, o curso proporciona formação consistente, unindo teoria e aplicabilidade prática.</p></section><div class="ucDuration"><strong>4 anos</strong><span>Duração do curso</span></div><a class="ucWhats" href="${WA}?text=Tenho%20interesse%20no%20curso%20de%20Matem%C3%A1tica" target="_blank" rel="noopener">💬 Tenho interesse neste curso</a></div></article>`);
    if(!document.getElementById('matematicaStyle')){const s=document.createElement('style');s.id='matematicaStyle';s.textContent=`#matematicaBlock{margin:14px 0;background:linear-gradient(135deg,#250632,#5b1685 72%,#70219b);border:1px solid #6f2890;border-radius:22px;padding:25px;box-shadow:0 15px 40px rgba(37,6,50,.2);position:relative;overflow:hidden;color:#fff}#matematicaBlock:before{content:"";position:absolute;left:0;top:0;bottom:0;width:6px;background:linear-gradient(#ff7000,#ff9b3f)}#matematicaBlock h3{color:#fff;font-size:29px;margin:9px 0 7px}.ucBtn{border:0;border-radius:12px;background:linear-gradient(135deg,#ff7000,#ff9b3f);color:#fff;padding:12px 16px;font-size:11px;font-weight:950;cursor:pointer}.ucPanel{margin-top:20px;padding:20px;border-radius:17px;background:#fff;color:#211827}.ucClose{border:0;background:#f1e8f5;color:#250632;border-radius:10px;padding:10px 13px;font-weight:900;cursor:pointer;margin-bottom:15px}.ucPanel h4{color:#250632;font-size:24px;margin:5px 0 18px}.ucPanel section{padding:17px 0;border-top:1px solid #eee7f1}.ucPanel h5{color:#5b1685;font-size:15px;margin:0 0 7px}.ucPanel p{color:#716576;font-size:12px;line-height:1.75}.ucMeta{display:flex;gap:7px;flex-wrap:wrap;margin:15px 0}.ucMeta span{padding:7px 10px;border-radius:9px;background:rgba(255,255,255,.1);color:#fff;font-size:9px;font-weight:900}.ucBadge{display:inline-flex;padding:6px 9px;border-radius:999px;background:rgba(255,255,255,.12);color:#ffb06a;font-size:9px;font-weight:1000;letter-spacing:.7px}.ucIntro{color:#eee3f2;font-size:12px;line-height:1.7}.ucDuration{display:flex;flex-direction:column;margin:17px 0;padding:15px;border-radius:14px;background:#250632;color:#fff}.ucDuration strong{font-size:20px;color:#ff9b3f}.ucDuration span{font-size:9px;color:#e8ddea}.ucWhats{border-radius:12px;background:linear-gradient(135deg,#ff7000,#ff9b3f);color:#fff;padding:12px 16px;font-size:11px;font-weight:950;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}@media(max-width:600px){#matematicaBlock{padding:20px 16px}.ucBtn,.ucWhats{width:100%}}`;document.head.appendChild(s)}
    const open=document.querySelector('[data-mat-open]'),close=document.querySelector('[data-mat-close]'),panel=document.querySelector('[data-mat-panel]');
    open.addEventListener('click',()=>{panel.hidden=false;panel.scrollIntoView({behavior:'smooth',block:'start'})});
    close.addEventListener('click',()=>{panel.hidden=true;document.getElementById('matematicaBlock').scrollIntoView({behavior:'smooth',block:'center'})});
  }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',()=>{render();setTimeout(render,700);setTimeout(render,1600)},{once:true}); else {render();setTimeout(render,700);setTimeout(render,1600)}
})();