(()=>{
'use strict';
const API='/api/matriculas',LOCAL='unifil_polo_matriculas_salvas_v1',OLD='unifil_matriculas_salvas_local_v2';
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};
const allLocal=()=>{const a=[...read(LOCAL),...read(OLD)],m=new Map();a.forEach(x=>{if(x&&x.nome)m.set(x.id||('local-'+x.nome+'-'+(x.criado_em||'')),x)});return[...m.values()]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function boot(){
 if(document.getElementById('matFeitasSection'))return;const nav=document.querySelector('.links');if(!nav)return setTimeout(boot,700);
 const style=document.createElement('style');style.textContent=`#matFeitasSection{display:none;position:fixed;inset:0;z-index:245;background:rgba(14,3,22,.84);backdrop-filter:blur(9px);padding:14px;overflow:auto}#matFeitasSection.open{display:block}.mfWrap{width:min(1000px,100%);margin:25px auto;background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 25px 90px rgba(0,0,0,.28)}.mfHead{padding:25px 28px;background:linear-gradient(135deg,#250632,#5b1685);color:#fff;display:flex;justify-content:space-between;gap:15px}.mfHead h2{margin:0;font-size:clamp(25px,4vw,36px)}.mfHead p{margin:7px 0 0;color:#eadff0;font-size:11px}.mfClose{width:44px;height:44px;border:0;border-radius:12px;background:rgba(255,255,255,.13);color:#fff;font-size:25px;cursor:pointer}.mfBody{padding:25px}.mfSearch{display:flex;gap:9px}.mfSearch input{flex:1;min-height:48px;border:2px solid #e4dbea;border-radius:13px;padding:10px 14px;font-size:13px}.mfSearch button{border:0;border-radius:13px;padding:10px 18px;background:#ff7000;color:#fff;font-weight:900;cursor:pointer}.mfCount{margin:16px 0 10px;color:#716576;font-size:11px;font-weight:800}.mfResults{display:grid;gap:10px}.mfItem{border:1px solid #e7dfeb;border-radius:15px;padding:15px;background:#fbf9fc}.mfName{color:#250632;font-size:15px;font-weight:950}.mfMeta{margin-top:5px;color:#716576;font-size:10px}.mfActions{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.mfView,.mfEdit,.mfDelete{border:0;border-radius:10px;padding:9px 13px;color:#fff;font-weight:900;cursor:pointer}.mfView{background:#250632}.mfEdit{background:#ff7000}.mfDelete{background:#b42318}.mfDetails{display:none;margin-top:12px;padding:15px;border-radius:12px;background:#fff;border:1px solid #e7dfeb;white-space:pre-wrap;font-size:11px;line-height:1.65;color:#392c3e}.mfDetails.open{display:block}.mfEmpty{padding:28px;text-align:center;border:1px dashed #d9cbe0;border-radius:15px;color:#716576;font-size:12px}.mfLoading{color:#5b1685;font-weight:900;font-size:11px}.mfConfirm{position:fixed;inset:0;z-index:300;display:flex;align-items:center;justify-content:center;background:rgba(14,3,22,.72);padding:18px}.mfConfirmBox{width:min(460px,100%);background:#fff;border-radius:20px;padding:24px;box-shadow:0 25px 80px rgba(0,0,0,.3)}.mfConfirmBox h3{margin:0 0 8px;color:#250632}.mfConfirmBox p{font-size:12px;color:#5e5164;line-height:1.6}.mfConfirmBtns{display:flex;gap:9px;justify-content:flex-end;margin-top:18px}.mfConfirmBtns button{border:0;border-radius:10px;padding:10px 15px;font-weight:900;cursor:pointer}.mfNo{background:#eee8f1;color:#250632}.mfYes{background:#b42318;color:#fff}@media(max-width:600px){#matFeitasSection{padding:5px}.mfWrap{margin:5px auto}.mfHead,.mfBody{padding:18px 15px}.mfSearch{display:grid}.mfSearch button{min-height:46px}.mfActions>*{flex:1;min-width:145px}}`;document.head.appendChild(style);
 const a=document.createElement('a');a.href='#matriculas-feitas';a.textContent='📋 Matrículas feitas';a.dataset.mfLink='4';nav.insertBefore(a,nav.querySelector('.cta')||null);
 const section=document.createElement('section');section.id='matFeitasSection';section.setAttribute('aria-hidden','true');section.innerHTML='<div class="mfWrap"><div class="mfHead"><div><h2>Matrículas feitas</h2><p>Pesquise pelo nome e abra, edite ou exclua a ficha preenchida.</p></div><button class="mfClose" type="button">×</button></div><div class="mfBody"><div class="mfSearch"><input id="mfBusca" type="search" placeholder="Digite o nome do aluno..." autocomplete="off"><button type="button" id="mfPesquisar">Pesquisar</button></div><div class="mfCount" id="mfCount">Digite um nome para pesquisar.</div><div class="mfResults" id="mfResults"></div></div></div>';document.body.appendChild(section);
 const input=section.querySelector('#mfBusca'),results=section.querySelector('#mfResults'),count=section.querySelector('#mfCount');
 const close=()=>{section.classList.remove('open');section.setAttribute('aria-hidden','true')};const open=()=>{section.classList.add('open');section.setAttribute('aria-hidden','false');input.focus()};a.onclick=e=>{e.preventDefault();open()};section.querySelector('.mfClose').onclick=close;section.onclick=e=>{if(e.target===section)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 function ficha(x){const d=x.dados||{};return Object.entries(d).filter(([k,v])=>String(v||'').trim()).map(([k,v])=>k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())+': '+v).join('\n')||'Nenhum campo preenchido foi encontrado.'}
 function salvarLocal(x){const keys=[LOCAL,OLD];keys.forEach(k=>{const arr=read(k).filter(y=>y.id!==x.id);if(x.id&&String(x.id).startsWith('local-'))arr.unshift(x);try{localStorage.setItem(k,JSON.stringify(arr.slice(0,1000)))}catch(e){}})}
 function abrirEdicao(x){const mat=document.getElementById('matriculasSection'),form=document.getElementById('matriculaForm');if(!mat||!form){alert('A ficha de matrícula não está disponível nesta página.');return}const d=x.dados||{};form.querySelectorAll('input,select,textarea').forEach(el=>{const n=el.name||el.id;if(!n||!(n in d))return;if(el.type==='radio'||el.type==='checkbox')el.checked=Array.isArray(d[n])?d[n].includes(el.value):String(d[n])===String(el.value);else el.value=d[n]});form.dataset.matriculaEditId=x.id||'';form.dataset.matriculaEditMode='1';const btn=document.getElementById('matSalvar');if(btn)btn.textContent='✏️ Atualizar matrícula';const msg=document.getElementById('matMsg');if(msg){msg.textContent='Editando matrícula de '+(x.nome||'aluno')+'. Altere os dados e clique em Atualizar matrícula.';msg.style.color='#5b1685';msg.style.fontWeight='800'}mat.classList.add('open');mat.setAttribute('aria-hidden','false');close();setTimeout(()=>form.querySelector('[name="nomeCompleto"]')?.focus(),150)}
 function confirmarExclusao(x,list){const overlay=document.createElement('div');overlay.className='mfConfirm';overlay.innerHTML=`<div class="mfConfirmBox"><h3>Excluir matrícula?</h3><p>Você está prestes a excluir a matrícula de <strong>${esc(x.nome||'Aluno')}</strong>. Esta ação remove o registro deste dispositivo e, quando o banco estiver conectado, também do banco do Polo.</p><div class="mfConfirmBtns"><button class="mfNo" type="button">Cancelar</button><button class="mfYes" type="button">Excluir matrícula</button></div></div>`;document.body.appendChild(overlay);overlay.querySelector('.mfNo').onclick=()=>overlay.remove();overlay.querySelector('.mfYes').onclick=async()=>{overlay.querySelector('.mfYes').disabled=true;overlay.querySelector('.mfYes').textContent='Excluindo...';let servidor=false;try{if(x.id&&!String(x.id).startsWith('local-')){const r=await fetch(API+'?id='+encodeURIComponent(x.id),{method:'DELETE',cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok&&d.ok)servidor=true;else if(r.status!==404&&r.status!==503)throw new Error(d.error||'Erro ao excluir')} }catch(e){alert('Não foi possível excluir no banco: '+(e.message||e));overlay.remove();return}salvarLocal({...x,id:x.id});[LOCAL,OLD].forEach(k=>{const arr=read(k).filter(y=>y.id!==x.id);try{localStorage.setItem(k,JSON.stringify(arr))}catch(e){}});overlay.remove();render(list.filter(y=>y.id!==x.id));count.textContent='Matrícula excluída com sucesso.'+(servidor?'':' Registro local removido.')}}
 function render(list){count.textContent=list.length+(list.length===1?' matrícula encontrada.':' matrículas encontradas.');results.innerHTML=list.length?list.map((x,i)=>`<div class="mfItem"><div class="mfName">${esc(x.nome||'Aluno sem nome')}</div><div class="mfMeta">${esc(x.curso||'Curso não informado')} • ${esc(x.data_solicitacao||'Data não informada')}</div><div class="mfActions"><button class="mfView" type="button" data-view="${i}">👁️ Ver matrícula preenchida</button><button class="mfEdit" type="button" data-edit="${i}">✏️ Editar matrícula</button><button class="mfDelete" type="button" data-delete="${i}">🗑️ Excluir matrícula</button></div><div class="mfDetails" id="mfD${i}">${esc(ficha(x))}</div></div>`).join(''):'<div class="mfEmpty">Nenhuma matrícula encontrada com esse nome.</div>';results.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const d=results.querySelector('#mfD'+b.dataset.view);d.classList.toggle('open');b.textContent=d.classList.contains('open')?'▲ Fechar matrícula':'👁️ Ver matrícula preenchida'});results.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>abrirEdicao(list[Number(b.dataset.edit)]));results.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>confirmarExclusao(list[Number(b.dataset.delete)],list))}
 async function search(){const nome=input.value.trim();results.innerHTML='<div class="mfLoading">Consultando matrículas...</div>';count.textContent='';const locais=allLocal().filter(x=>!nome||String(x.nome||'').toLocaleLowerCase().includes(nome.toLocaleLowerCase()));try{const r=await fetch(API+'?nome='+encodeURIComponent(nome),{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error('API indisponível');const map=new Map();[...locais,...(d.matriculas||[])].forEach(x=>{if(x&&x.nome)map.set(x.id||('server-'+x.nome+'-'+(x.criado_em||'')),x)});render([...map.values()])}catch(e){render(locais)}}
 section.querySelector('#mfPesquisar').onclick=search;input.onkeydown=e=>{if(e.key==='Enter')search()};input.oninput=()=>{if(!input.value.trim()){results.innerHTML='';count.textContent='Digite um nome para pesquisar.'}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
