(()=>{
'use strict';
const API='/api/matriculas',LOCAL='unifil_polo_matriculas_salvas_v1',OLD='unifil_matriculas_salvas_local_v2';
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}};
const allLocal=()=>{const a=[...read(LOCAL),...read(OLD)],m=new Map();a.forEach(x=>{if(x&&x.nome)m.set(x.id||('local-'+x.nome+'-'+(x.criado_em||'')),x)});return[...m.values()]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function boot(){
 if(document.getElementById('matFeitasSection'))return;const nav=document.querySelector('.links');if(!nav)return setTimeout(boot,700);
 const style=document.createElement('style');style.textContent=`#matFeitasSection{display:none;position:fixed;inset:0;z-index:245;background:rgba(14,3,22,.84);backdrop-filter:blur(9px);padding:14px;overflow:auto}#matFeitasSection.open{display:block}.mfWrap{width:min(1000px,100%);margin:25px auto;background:#fff;border-radius:24px;overflow:hidden;box-shadow:0 25px 90px rgba(0,0,0,.28)}.mfHead{padding:25px 28px;background:linear-gradient(135deg,#250632,#5b1685);color:#fff;display:flex;justify-content:space-between;gap:15px}.mfHead h2{margin:0;font-size:clamp(25px,4vw,36px)}.mfHead p{margin:7px 0 0;color:#eadff0;font-size:11px}.mfClose{width:44px;height:44px;border:0;border-radius:12px;background:rgba(255,255,255,.13);color:#fff;font-size:25px;cursor:pointer}.mfBody{padding:25px}.mfSearch{display:flex;gap:9px}.mfSearch input{flex:1;min-height:48px;border:2px solid #e4dbea;border-radius:13px;padding:10px 14px;font-size:13px}.mfSearch button{border:0;border-radius:13px;padding:10px 18px;background:#ff7000;color:#fff;font-weight:900;cursor:pointer}.mfCount{margin:16px 0 10px;color:#716576;font-size:11px;font-weight:800}.mfResults{display:grid;gap:10px}.mfItem{border:1px solid #e7dfeb;border-radius:15px;padding:15px;background:#fbf9fc}.mfName{color:#250632;font-size:15px;font-weight:950}.mfMeta{margin-top:5px;color:#716576;font-size:10px}.mfActions{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.mfView{border:0;border-radius:10px;padding:9px 13px;background:#250632;color:#fff;font-weight:900;cursor:pointer}.mfDetails{display:none;margin-top:12px;padding:15px;border-radius:12px;background:#fff;border:1px solid #e7dfeb;white-space:pre-wrap;font-size:11px;line-height:1.65;color:#392c3e}.mfDetails.open{display:block}.mfEmpty{padding:28px;text-align:center;border:1px dashed #d9cbe0;border-radius:15px;color:#716576;font-size:12px}.mfLoading{color:#5b1685;font-weight:900;font-size:11px}@media(max-width:600px){#matFeitasSection{padding:5px}.mfWrap{margin:5px auto}.mfHead,.mfBody{padding:18px 15px}.mfSearch{display:grid}.mfSearch button{min-height:46px}}`;document.head.appendChild(style);
 const a=document.createElement('a');a.href='#matriculas-feitas';a.textContent='📋 Matrículas feitas';a.dataset.mfLink='2';nav.insertBefore(a,nav.querySelector('.cta')||null);
 const section=document.createElement('section');section.id='matFeitasSection';section.setAttribute('aria-hidden','true');section.innerHTML='<div class="mfWrap"><div class="mfHead"><div><h2>Matrículas feitas</h2><p>Pesquise pelo nome e abra a ficha preenchida.</p></div><button class="mfClose" type="button">×</button></div><div class="mfBody"><div class="mfSearch"><input id="mfBusca" type="search" placeholder="Digite o nome do aluno..." autocomplete="off"><button type="button" id="mfPesquisar">Pesquisar</button></div><div class="mfCount" id="mfCount">Digite um nome para pesquisar.</div><div class="mfResults" id="mfResults"></div></div></div>';document.body.appendChild(section);
 const input=section.querySelector('#mfBusca'),results=section.querySelector('#mfResults'),count=section.querySelector('#mfCount');
 const close=()=>{section.classList.remove('open');section.setAttribute('aria-hidden','true')};const open=()=>{section.classList.add('open');section.setAttribute('aria-hidden','false');input.focus()};a.onclick=e=>{e.preventDefault();open()};section.querySelector('.mfClose').onclick=close;section.onclick=e=>{if(e.target===section)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 function ficha(x){const d=x.dados||{};return Object.entries(d).filter(([k,v])=>String(v||'').trim()).map(([k,v])=>k.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())+': '+v).join('\n')||'Nenhum campo preenchido foi encontrado.'}
 function render(list){count.textContent=list.length+(list.length===1?' matrícula encontrada.':' matrículas encontradas.');results.innerHTML=list.length?list.map((x,i)=>`<div class="mfItem"><div class="mfName">${esc(x.nome||'Aluno sem nome')}</div><div class="mfMeta">${esc(x.curso||'Curso não informado')} • ${esc(x.data_solicitacao||'Data não informada')}</div><div class="mfActions"><button class="mfView" type="button" data-view="${i}">👁️ Ver matrícula preenchida</button></div><div class="mfDetails" id="mfD${i}">${esc(ficha(x))}</div></div>`).join(''):'<div class="mfEmpty">Nenhuma matrícula encontrada com esse nome.</div>';results.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const d=results.querySelector('#mfD'+b.dataset.view);d.classList.toggle('open');b.textContent=d.classList.contains('open')?'▲ Fechar matrícula':'👁️ Ver matrícula preenchida'})}
 async function search(){const nome=input.value.trim();results.innerHTML='<div class="mfLoading">Consultando matrículas...</div>';count.textContent='';const locais=allLocal().filter(x=>!nome||String(x.nome||'').toLocaleLowerCase().includes(nome.toLocaleLowerCase()));try{const r=await fetch(API+'?nome='+encodeURIComponent(nome),{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error('API indisponível');const map=new Map();[...locais,...(d.matriculas||[])].forEach(x=>{if(x&&x.nome)map.set(x.id||('server-'+x.nome+'-'+(x.criado_em||'')),x)});render([...map.values()])}catch(e){render(locais)}}
 section.querySelector('#mfPesquisar').onclick=search;input.onkeydown=e=>{if(e.key==='Enter')search()};input.oninput=()=>{if(!input.value.trim()){results.innerHTML='';count.textContent='Digite um nome para pesquisar.'}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();