(()=>{
'use strict';
const WA='https://wa.me/5544997239673';
const KEY='unifil_polo_matricula_rascunho_v1';
function css(){
 if(document.getElementById('matriculasStyle')) return;
 const s=document.createElement('style');s.id='matriculasStyle';s.textContent=`
 #matriculasSection{display:none;position:fixed;inset:0;z-index:240;background:rgba(14,3,22,.82);backdrop-filter:blur(9px);padding:12px;overflow:auto}
 #matriculasSection.open{display:block}
 .matWrap{width:min(1080px,100%);margin:0 auto;background:#fff;border-radius:24px;box-shadow:0 24px 80px rgba(0,0,0,.25);overflow:hidden}
 .matHead{background:linear-gradient(135deg,#250632,#5b1685);color:#fff;padding:25px 28px;display:flex;justify-content:space-between;gap:18px;align-items:flex-start;position:sticky;top:0;z-index:3}
 .matHead h2{margin:0;font-size:clamp(25px,4vw,39px);line-height:1.05}.matHead p{margin:8px 0 0;color:#eadff0;font-size:12px}.matClose{border:0;background:rgba(255,255,255,.12);color:#fff;width:44px;height:44px;border-radius:12px;font-size:25px;cursor:pointer;flex:none}
 .matForm{padding:25px 28px 30px}.matIntro{border:1px solid #eadff0;background:#fbf8fc;border-radius:15px;padding:13px 15px;margin-bottom:20px;color:#5e5164;font-size:11px}.matSection{border:1px solid #e7dfeb;border-radius:18px;margin:14px 0;overflow:hidden;background:#fff}.matTitle{background:#250632;color:#fff;padding:11px 15px;font-size:11px;font-weight:950;letter-spacing:.6px;text-transform:uppercase}.matGrid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px;padding:16px}.matField{grid-column:span 4}.matField.w6{grid-column:span 6}.matField.w8{grid-column:span 8}.matField.w12{grid-column:1/-1}.matField label{display:block;color:#493d50;font-size:10px;font-weight:900;margin-bottom:5px}.matField input,.matField select,.matField textarea{width:100%;min-height:43px;border:1px solid #dcd2e2;border-radius:10px;background:#fff;padding:9px 10px;color:#25182b;outline:none;font:inherit;font-size:11px}.matField textarea{min-height:75px;resize:vertical}.matField input:focus,.matField select:focus,.matField textarea:focus{border-color:#7a2da4;box-shadow:0 0 0 3px rgba(91,22,133,.08)}.matChecks{display:flex;gap:12px;flex-wrap:wrap}.matCheck{display:flex;align-items:center;gap:6px;font-size:10px;font-weight:800;color:#51465a}.matCheck input{width:16px;height:16px}.matDocs{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:16px}.matDoc{border:1px solid #e7dfeb;border-radius:13px;padding:11px;background:#fbf9fc}.matDoc label{display:flex;gap:8px;align-items:center;font-size:10px;font-weight:850;color:#3e3344}.matDoc input{margin-top:8px;width:100%;font-size:9px}.matActions{display:flex;gap:9px;flex-wrap:wrap;margin-top:20px;position:sticky;bottom:0;background:rgba(255,255,255,.96);padding-top:12px}.matBtn{border:0;border-radius:12px;min-height:46px;padding:10px 17px;font-size:11px;font-weight:950;cursor:pointer}.matPrimary{background:linear-gradient(135deg,#ff7000,#ff9b3f);color:#fff}.matSecondary{background:#f2edf5;color:#250632}.matGreen{background:#250632;color:#fff}.matMsg{font-size:10px;color:#716576;align-self:center}.matRequired{color:#ff7000}.matDeclaration{font-size:11px;color:#4f4355;line-height:1.7}.matDeclaration label{display:flex;gap:8px;align-items:flex-start}.matDeclaration input{margin-top:3px;width:17px;height:17px}.matFooterNote{font-size:9px;color:#817486;margin-top:10px}
 @media(max-width:760px){#matriculasSection{padding:5px}.matHead{padding:20px 16px}.matForm{padding:18px 14px 22px}.matGrid{grid-template-columns:1fr;gap:10px;padding:13px}.matField,.matField.w6,.matField.w8,.matField.w12{grid-column:1/-1}.matDocs{grid-template-columns:1fr;padding:13px}.matActions{display:grid}.matActions>*{width:100%}.matMsg{text-align:center}}
 `;document.head.appendChild(s)
}
function el(tag,attrs={},html=''){const e=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(html)e.innerHTML=html;return e}
function field(id,label,type='text',cls='w4',extra=''){return `<div class="matField ${cls}"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" ${extra}></div>`}
function build(){
 css();
 if(document.getElementById('matriculasSection')) return;
 const nav=document.querySelector('.links');
 if(nav&&!nav.querySelector('[data-matriculas-link]')){const a=el('a',{'href':'#matriculas','data-matriculas-link':'1','class':'matNav'} ,'📝 Matrículas');a.style.background='#250632';a.style.color='#fff';nav.insertBefore(a,nav.querySelector('.cta')||null);a.addEventListener('click',e=>{e.preventDefault();open()})}
 const section=el('section',{id:'matriculasSection','aria-hidden':'true'});
 section.innerHTML=`<div class="matWrap"><div class="matHead"><div><h2>Ficha de Matrícula</h2><p>Graduação Online • Preencha todos os campos com letra legível e de forma completa.</p></div><button class="matClose" type="button" aria-label="Fechar matrícula">×</button></div><form class="matForm" id="matriculaForm" autocomplete="on"><div class="matIntro"><strong>Ficha de matrícula UniFil</strong><br>O formulário abaixo foi montado com base na ficha enviada pelo Polo. Os campos marcados com <span class="matRequired">*</span> devem ser preenchidos quando aplicáveis.</div>
 <div class="matSection"><div class="matTitle">1. Dados do curso</div><div class="matGrid">${field('cursoGraduacao','Curso de graduação *','text','w8')}<div class="matField w4"><label for="dataSolicitacao">Data da solicitação *</label><input id="dataSolicitacao" name="dataSolicitacao" type="date"></div><div class="matField w6"><label>Modalidade *</label><div class="matChecks"><label class="matCheck"><input type="radio" name="modalidade" value="Online"> Online</label><label class="matCheck"><input type="radio" name="modalidade" value="Semipresencial"> Semipresencial</label></div></div><div class="matField w6"><label>Turno</label><div class="matChecks"><label class="matCheck"><input type="radio" name="turno" value="Manhã"> Manhã</label><label class="matCheck"><input type="radio" name="turno" value="Tarde"> Tarde</label><label class="matCheck"><input type="radio" name="turno" value="Noite"> Noite</label><label class="matCheck"><input type="radio" name="turno" value="Flexível"> Flexível</label></div></div></div></div>
 <div class="matSection"><div class="matTitle">2. Dados pessoais</div><div class="matGrid">${field('nomeCompleto','Nome completo *','text','w6')}${field('nomeSocial','Nome social (se houver)','text','w6')}${field('dataNascimento','Data de nascimento *','date','w4')}${field('naturalidade','Naturalidade','text','w4')}${field('nacionalidade','Nacionalidade','text','w4')}${field('cpf','CPF *','text','w4','inputmode="numeric"')}${field('rg','RG','text','w4')}${field('orgaoEmissor','Órgão emissor','text','w4')}${field('ufRg','UF do RG','text','w4','maxlength="2"')}${field('dataExpedicao','Data de expedição','date','w4')}${field('tituloEleitor','Título de eleitor','text','w4')}${field('zona','Zona','text','w4')}${field('secao','Seção','text','w4')}${field('endereco','Endereço completo *','text','w8')}${field('numero','Nº *','text','w4')}${field('complemento','Complemento','text','w4')}${field('bairro','Bairro *','text','w4')}${field('cidade','Cidade *','text','w4')}${field('ufEndereco','UF *','text','w4','maxlength="2"')}${field('cep','CEP *','text','w4','inputmode="numeric"')}${field('email','E-mail *','email','w6')}${field('telefoneFixo','Telefone fixo','tel','w6')}${field('celular','Celular/WhatsApp *','tel','w6')}${field('profissao','Profissão','text','w6')}<div class="matField w6"><label>Sexo</label><div class="matChecks"><label class="matCheck"><input type="radio" name="sexo" value="Masculino"> Masculino</label><label class="matCheck"><input type="radio" name="sexo" value="Feminino"> Feminino</label><label class="matCheck"><input type="radio" name="sexo" value="Outro"> Outro</label></div></div><div class="matField w6"><label for="estadoCivil">Estado civil</label><select id="estadoCivil" name="estadoCivil"><option value="">Selecione</option><option>Solteiro(a)</option><option>Casado(a)</option><option>Divorciado(a)</option><option>Viúvo(a)</option><option>União estável</option><option>Outro</option></select></div></div></div>
 <div class="matSection"><div class="matTitle">3. Dados do responsável financeiro (se for diferente do aluno)</div><div class="matGrid">${field('respNome','Nome completo','text','w6')}${field('respCpf','CPF','text','w6','inputmode="numeric"')}${field('respRelacao','Grau de parentesco ou relação','text','w6')}${field('respTelefone','Telefone','tel','w6')}${field('respEmail','E-mail','email','w6')}${field('respProfissao','Profissão','text','w6')}</div></div>
 <div class="matSection"><div class="matTitle">4. Escolaridade</div><div class="matGrid">${field('ensinoMedioData','Ensino médio concluído em','date','w4')}${field('escolaMedio','Escola','text','w8')}${field('cidadeEscola','Cidade','text','w4')}${field('ufEscola','UF','text','w4','maxlength="2"')}<div class="matField w4"><label>Tipo de escola</label><div class="matChecks"><label class="matCheck"><input type="radio" name="tipoEscola" value="Pública"> Pública</label><label class="matCheck"><input type="radio" name="tipoEscola" value="Privada"> Privada</label></div></div></div></div>
 <div class="matSection"><div class="matTitle">5. Documentação (anexar cópias)</div><div class="matDocs"><div class="matDoc"><label><input type="checkbox" name="docRg"> RG</label><input type="file" name="fileRg" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docHistorico"> Histórico do ensino médio</label><input type="file" name="fileHistorico" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docCpf"> CPF</label><input type="file" name="fileCpf" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docConclusao"> Certificado de conclusão do ensino médio</label><input type="file" name="fileConclusao" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docCertidao"> Certidão de nascimento ou casamento</label><input type="file" name="fileCertidao" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docEleitor"> Título de eleitor (maiores de 18 anos)</label><input type="file" name="fileEleitor" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docEndereco"> Comprovante de endereço</label><input type="file" name="fileEndereco" accept="image/*,.pdf"></div><div class="matDoc"><label><input type="checkbox" name="docMilitar"> Certificado militar (para homens)</label><input type="file" name="fileMilitar" accept="image/*,.pdf"></div></div></div>
 <div class="matSection"><div class="matTitle">6. Informações adicionais</div><div class="matGrid"><div class="matField w12"><label>Como ficou sabendo da UniFil?</label><div class="matChecks"><label class="matCheck"><input type="checkbox" name="origemInternet"> Internet</label><label class="matCheck"><input type="checkbox" name="origemRedes"> Redes sociais</label><label class="matCheck"><input type="checkbox" name="origemIndicacao"> Indicação</label></div></div>${field('origemOutros','Outros','text','w12')}${field('outraGraduacaoCurso','Se sim, qual curso?','text','w8')}<div class="matField w4"><label>Já possui outra graduação?</label><div class="matChecks"><label class="matCheck"><input type="radio" name="outraGraduacao" value="Sim"> Sim</label><label class="matCheck"><input type="radio" name="outraGraduacao" value="Não"> Não</label></div></div></div></div>
 <div class="matSection"><div class="matTitle">7. Declaração</div><div class="matGrid"><div class="matField w12"><div class="matDeclaration"><label><input type="checkbox" id="declaracao" name="declaracao"><span>Declaro que as informações acima são verdadeiras e assumo total responsabilidade pelas mesmas.</span></label></div></div>${field('assinaturaAluno','Assinatura do aluno','text','w8')}${field('dataDeclaracao','Data','date','w4')}</div></div>
 <div class="matActions"><button class="matBtn matPrimary" type="button" id="matSalvar">💾 Salvar preenchimento</button><button class="matBtn matSecondary" type="button" id="matLimpar">↺ Limpar formulário</button><button class="matBtn matGreen" type="button" id="matImprimir">🖨️ Imprimir ficha</button><span class="matMsg" id="matMsg">Preencha a ficha e salve o rascunho para não perder os dados.</span></div><div class="matFooterNote">A ficha original informa que a documentação deve ser anexada em cópia. Os arquivos selecionados ficam vinculados ao preenchimento desta página enquanto a ficha estiver aberta.</div>
 </form></div>`;
 document.body.appendChild(section);
 const form=section.querySelector('#matriculaForm');
 const close=section.querySelector('.matClose');
 function open(){section.classList.add('open');section.setAttribute('aria-hidden','false');loadDraft();window.scrollTo({top:0,behavior:'smooth'})}
 function shut(){section.classList.remove('open');section.setAttribute('aria-hidden','true')}
 close.onclick=shut;section.addEventListener('click',e=>{if(e.target===section)shut()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&section.classList.contains('open'))shut()});
 function values(){const data={};form.querySelectorAll('input,select,textarea').forEach(x=>{if(x.type==='file')return;if(x.type==='radio'||x.type==='checkbox'){if(x.checked)data[x.name||x.id]=x.value==='on'?true:x.value}else data[x.name]=x.value});return data}
 function save(){try{localStorage.setItem(KEY,JSON.stringify(values()));section.querySelector('#matMsg').textContent='Rascunho salvo neste dispositivo.'}catch(e){section.querySelector('#matMsg').textContent='Não foi possível salvar o rascunho neste dispositivo.'}}
 function loadDraft(){try{const data=JSON.parse(localStorage.getItem(KEY)||'{}');Object.entries(data).forEach(([k,v])=>{const els=form.querySelectorAll(`[name="${CSS.escape(k)}"]`);els.forEach(x=>{if(x.type==='radio'||x.type==='checkbox')x.checked=x.value===v||v===true;else x.value=v})})}catch(e){}}
 form.querySelector('#matSalvar').onclick=save;
 form.querySelector('#matLimpar').onclick=()=>{if(confirm('Limpar todos os dados preenchidos desta ficha?')){form.reset();localStorage.removeItem(KEY);section.querySelector('#matMsg').textContent='Formulário limpo.'}};
 form.querySelector('#matImprimir').onclick=()=>window.print();
 const printStyle=document.createElement('style');printStyle.textContent=`@media print{body>*:not(#matriculasSection){display:none!important}#matriculasSection{display:block!important;position:static!important;background:#fff!important;padding:0!important;overflow:visible!important}#matriculasSection .matWrap{box-shadow:none!important;width:100%!important}#matriculasSection .matHead{position:static!important;color:#000!important;background:#fff!important;border-bottom:2px solid #000}#matriculasSection .matHead p{color:#000!important}#matriculasSection .matClose,#matriculasSection .matActions,.matFooterNote{display:none!important}.matSection{break-inside:avoid}.matField input,.matField select,.matField textarea{border:1px solid #777!important}.matDocs{grid-template-columns:1fr 1fr!important}}`;document.head.appendChild(printStyle);
 return {open,shut}
}
function start(){const api=build();window.openMatricula=api.open;const a=document.querySelector('[data-matriculas-link]');if(a)a.addEventListener('click',e=>{e.preventDefault();api.open()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();