/* UniFil Polo Iguaraçu — Grade curricular de Teologia Bacharelado */
(function(){
'use strict';
const disciplinasObrigatorias=[
['Teologia Prática e Espiritualidade Cristã',90],['Gestão e Cultura Bíblica',90],['Gestão e Liderança Cristã',90],['História do Cristianismo I',90],['História do Cristianismo II',90],['Introdução aos Estudos Teológicos',90],['Panorama do Antigo e do Novo Testamento',90],['Capelania Cristã',90],['Missão Transcultura e Teologia Urbana',90],['Extensão I',50],['Mentoria',90],['Teologia Contemporânea',90],['Extensão II',50],['Teologia e Ecologia',90],['Psicologia da Religião',90],['Extensão III',50],['Estágio I',50],['Pedagogia da Educação Cristã',90],['Hermenêutica e Homilética',90],['Extensão IV',50],['Estágio II',50],['Metodologia Prática para a Teologia',90],['Teologia Sistemática I',90],['Extensão V',50],['Estágio III',50],['Grego e Exegese no Novo Testamento',90],['Teologia Sistemática II',90],['Extensão VI',50],['Estágio IV',50],['Hebraico e Exegese no Antigo Testamento',90],['Teologia Sistemática III',90],['Sociologia e Antropologia da Religião',90],['Filosofia da Religião',90],['Trabalho de Conclusão de Curso – TCC',100]
];
const optativas=[['Evangelização e Discipulado',90],['Liturgia do Culto Cristão',90],['Evangelização e discipulado',90],['PAMB – Política de Educação Ambiental',90],['ETNR - Educação das Relações Étnicos Raciais',90],['Língua Brasileira de Sinais – LIBRAS',90]];
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function tabela(arr){return arr.map((d,i)=>`<div class="tgRow"><span>${i+1}</span><strong>${esc(d[0])}</strong><b>${d[1]} h/a</b></div>`).join('');}
function render(){
 const block=document.getElementById('teologiaFixBlock');
 if(!block||document.getElementById('teologiaGradeBtn')) return;
 const body=block.querySelector('#teologiaFixBody');
 if(!body) return;
 const style=document.createElement('style');style.id='teologiaGradeStyle';style.textContent=`
 .tgActions{display:flex;gap:9px;flex-wrap:wrap;margin-top:18px}.tgBtn{border:0;border-radius:12px;padding:12px 17px;background:#5b1685;color:#fff;font-size:10px;font-weight:900;cursor:pointer}.tgBtn:hover{background:#ff7000}.tgModal{position:fixed;inset:0;z-index:99999;background:rgba(14,3,22,.82);display:flex;align-items:center;justify-content:center;padding:18px}.tgPanel{width:min(900px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;box-shadow:0 25px 80px rgba(0,0,0,.35);color:#211827}.tgHead{padding:24px;background:linear-gradient(135deg,#250632,#5b1685);color:#fff;position:sticky;top:0;z-index:2}.tgHead h2{margin:0 0 7px;font-size:24px}.tgHead p{margin:0;color:#eee5f2;font-size:11px;line-height:1.6}.tgClose{position:absolute;right:18px;top:18px;border:0;border-radius:10px;width:36px;height:36px;background:rgba(255,255,255,.14);color:#fff;font-size:20px;cursor:pointer}.tgContent{padding:22px}.tgSection{border:1px solid #e7dfeb;border-radius:16px;overflow:hidden;margin-bottom:18px}.tgSection h3{margin:0;padding:13px 15px;background:#f6f1f8;color:#5b1685;font-size:12px}.tgRow{display:grid;grid-template-columns:35px 1fr 70px;gap:10px;align-items:center;padding:11px 14px;border-top:1px solid #eee8f0;font-size:11px}.tgRow span{color:#8c7b91;font-weight:800}.tgRow strong{font-weight:700}.tgRow b{font-size:10px;text-align:right;color:#ff7000}.tgInfo{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.tgInfo div{background:#fbf9fc;border:1px solid #e7dfeb;border-radius:14px;padding:14px}.tgInfo strong{display:block;color:#5b1685;font-size:10px;margin-bottom:5px}.tgInfo span{font-size:11px;font-weight:800}@media(max-width:680px){.tgActions{display:grid}.tgActions>*{width:100%}.tgInfo{grid-template-columns:1fr 1fr}.tgRow{grid-template-columns:28px 1fr 58px;font-size:10px}.tgContent{padding:14px}}
 `;document.head.appendChild(style);
 const actions=body.querySelector('div:last-child');
 const btn=document.createElement('button');btn.id='teologiaGradeBtn';btn.className='tgBtn';btn.type='button';btn.textContent='📚 Ver grade de disciplinas';
 actions.insertBefore(btn,actions.firstChild);
 const modal=document.createElement('div');modal.className='tgModal';modal.hidden=true;modal.innerHTML=`<div class="tgPanel" role="dialog" aria-modal="true" aria-labelledby="tgTitle"><div class="tgHead"><button class="tgClose" type="button" aria-label="Fechar">×</button><h2 id="tgTitle">Grade curricular — Teologia Bacharelado</h2><p>Modalidade a Distância — EaD • 03 anos / 06 semestres</p></div><div class="tgContent"><div class="tgSection"><h3>Disciplinas obrigatórias • CH (60') / H/A</h3>${tabela(disciplinasObrigatorias)}</div><div class="tgSection"><h3>Disciplinas optativas • CH (60') / H/A</h3>${tabela(optativas)}</div><div class="tgInfo"><div><strong>Componentes Curriculares</strong><span>2.960 horas</span></div><div><strong>Estágios Supervisionados</strong><span>200 horas</span></div><div><strong>TCC</strong><span>100 horas</span></div><div><strong>Atividades Complementares</strong><span>200 horas</span></div></div><div style="margin-top:14px;border-radius:14px;padding:15px;background:#fbf9fc;border:1px solid #e7dfeb"><strong style="color:#5b1685;font-size:10px">Carga Horária Total do Curso</strong><div style="font-size:20px;font-weight:900;color:#250632;margin-top:4px">3.460 horas (60’)</div><p style="font-size:10px;line-height:1.7;color:#716576;margin:8px 0 0">Disciplina optativa: o aluno pode optar por acrescentar LIBRAS, Educação das Relações Étnico Raciais (ETNR) e Políticas de Educação Ambiental (PAMB) ao currículo, conforme as condições apresentadas na grade curricular.</p><p style="font-size:10px;line-height:1.7;color:#716576;margin:7px 0 0">Obs.: a ordem da oferta das disciplinas será estipulada conforme o mês de ingresso do aluno no curso.</p></div></div></div>`;
 document.body.appendChild(modal);
 const close=modal.querySelector('.tgClose');btn.onclick=()=>{modal.hidden=false;document.body.style.overflow='hidden'};function fechar(){modal.hidden=true;document.body.style.overflow=''}close.onclick=fechar;modal.onclick=e=>{if(e.target===modal)fechar()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)fechar()});
}
function boot(){render();[100,400,900,1800,3000].forEach(ms=>setTimeout(render,ms));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();